# Supervised learning algorithms
include(joinpath("supervised_learning", "baseRegression.jl"))
include(joinpath("supervised_learning", "decisionTree.jl"))
include(joinpath("supervised_learning", "gaussianDiscriminantAnalysis.jl"))
include(joinpath("supervised_learning", "hiddenMarkovModel.jl"))
include(joinpath("supervised_learning", "kNearestNeighbors.jl"))
include(joinpath("supervised_learning", "labelPropagation.jl"))
include(joinpath("supervised_learning", "linearDiscriminantAnalysis.jl"))
include(joinpath("supervised_learning", "naivdBayes.jl"))
include(joinpath("supervised_learning", "neuralNetwork_bp.jl"))
include(joinpath("supervised_learning", "support_vector_machine.jl"))
include(joinpath("supervised_learning", "adaboost.jl"))
include(joinpath("supervised_learning", "randomForests.jl"))
include(joinpath("supervised_learning", "xgboost.jl"))
include(joinpath("supervised_learning", "GradientBoostingTree.jl"))
